# See https://pre-commit.com for more information

default_language_version:
  python: python3.9
default_install_hook_types: [pre-commit, post-checkout, post-merge]
repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        description: trims trailing whitespace.
        entry: uv run trailing-whitespace-fixer
        language: system
        name: trim trailing whitespace
        pass_filenames: true
        stages: [commit, manual]
        exclude_types: [python, pyi]
        types: [text]

      - id: end-of-file-fixer
        description: ensures that a file is either empty, or ends with one newline.
        entry: uv run end-of-file-fixer
        language: system
        name: fix end of files
        pass_filenames: true
        stages: [commit, manual]
        exclude_types: [python, pyi]
        types: [text]

      - id: uv-check
        name: uv check
        description: run uv lock to validate config
        entry: uv run uv lock --locked
        language: system
        pass_filenames: false
        files: ^(.*/)?pyproject\.toml|(.*/)?uv\.lock$
        stages: [commit]

      - id: uv-sync
        name: uv sync
        description: run uv sync to install dependencies from the lock file
        entry: uv run uv sync
        language: system
        pass_filenames: false
        stages: [post-checkout, post-merge]
        always_run: true

      - id: ruff-check
        entry: uv run ruff check --fix --show-fixes
        language: system
        name: ruff check
        pass_filenames: true
        require_serial: true
        types_or: [python, pyi]
        stages: [commit]

      - id: ruff-format
        entry: uv run ruff format
        language: system
        name: ruff format
        pass_filenames: true
        require_serial: true
        types_or: [python, pyi]
        stages: [commit]

      - id: pytest
        entry: uv run pytest .
        language: system
        name: pytest
        pass_filenames: false
        require_serial: true
        types_or: [python, pyi]
        stages: [commit]

      - id: pyright
        entry: uv run pyright .
        language: system
        name: pyright
        pass_filenames: false
        require_serial: true
        types_or: [python, pyi]
        stages: [commit]
