# See https://pre-commit.com for more information

default_language_version:
  python: python3.9
default_install_hook_types: [pre-commit, post-checkout, post-merge]
repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        description: trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: system
        name: trim trailing whitespace
        pass_filenames: true
        stages: [commit, manual]
        exclude_types: [python, pyi]
        types: [text]

      - id: end-of-file-fixer
        description: ensures that a file is either empty, or ends with one newline.
        entry: end-of-file-fixer
        language: system
        name: fix end of files
        pass_filenames: true
        stages: [commit, manual]
        exclude_types: [python, pyi]
        types: [text]

      - id: poetry-check
        name: poetry check
        description: run poetry check to validate config
        entry: poetry check
        language: system
        pass_filenames: false
        files: ^(.*/)?pyproject\.toml$
        stages: [commit]

      - id: poetry-install
        name: poetry install
        description: run poetry install to install dependencies from the lock file
        entry: poetry install --with dev
        language: system
        pass_filenames: false
        stages: [post-checkout, post-merge]
        always_run: true

      - id: ruff-check
        entry: ruff check --fix --show-fixes
        language: system
        name: ruff check
        pass_filenames: true
        require_serial: true
        types_or: [python, pyi]
        stages: [commit]

      - id: ruff-format
        entry: ruff format
        language: system
        name: ruff format
        pass_filenames: true
        require_serial: true
        types_or: [  python, pyi ]
        stages: [ commit ]

      - id: pytest
        entry: pytest .
        language: system
        name: pytest
        pass_filenames: false
        require_serial: true
        types_or: [  python, pyi ]
        stages: [ commit ]

      - id: pyright
        entry: pyright .
        language: system
        name: pyright
        pass_filenames: false
        require_serial: true
        types_or: [  python, pyi ]
        stages: [ commit ]
