exclude = [".git"]
line-length = 88
target-version = "py39"

[lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = [
    "ANN101", # Missing type annotation for `self` in method
    "D203",   # one-blank-line-before-class
    "COM812", # missing-trailing-comma
    "ISC001", # single-line-implicit-string-concatenation
    "D102",   # Missing docstring in public method
    "D101",   # Missing docstring in public class
    "S101",   # Use of `assert` detected
    "D103",   # Missing docstring in public function
    "D100",   # Missing docstring in public module
]

[lint.pydocstyle]
convention = "pep257"
